require "employ_crawler/base"
require "employ_crawler/jnedu_crawler"
require "employ_crawler/zdjw_crawler"
require "employ_crawler/ytedu_crawler"
require "employ_crawler/qdedu_crawler"
require "employ_crawler/code_mapping"
require "employ_crawler/version"
